name: Deploy and Clear Cache

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy application
        run: |
          ./deploy.sh

      - name: Clear Redis cache
        run: |
          ./clear-cache.sh
